# Generated by Django 4.2.5 on 2023-10-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_rename_owner_survey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Text of the answer'),
        ),
    ]
